# No user@hostname, dont need.
# Show current git branch name if exists
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

# git commit -m date # I.e. I dont care what the commit message is as I am going to rebase / rewrite later
alias gcmd='git commit -m `date +%Y%m%d-%H%M%S`'

# git push origin $branch name (current branch name goes to remote of same name)
# You can also `gpob --force` and it will force push
alias gpob='git push origin `git rev-parse --abbrev-ref HEAD`'

# grh - git reset head. Defaults to 1 without specifying how many, but will reset by any positive integer.
# grh 2 will go back 2 commits
function grh () {
  local count="${1:-1}"
  if ! [[ "$count" =~ ^[0-9]+$ ]] || [ "$count" -eq 0 ]; then
    echo "Error: Please provide a valid positive integer." >&2
    return 1
  fi


  # Ensure the input is a positive integer
  git reset "HEAD~$count"
}
